name: storm_sense
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  dio: ^5.4.0
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.0.0
  freezed_annotation: ^3.0.0
  equatable: ^2.0.0
  json_annotation: ^4.9.0
  go_router: ^14.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  freezed: ^3.0.0
  json_serializable: ^6.11.0
  bloc_test: ^9.1.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
